---
- hosts: localhost

  tasks:
    - name: "HOSTNAME"
      hostname: name=django

    - name: "REMOVENDO PACOTES"
      yum: pkg={{ item }} state=absent
      with_items:
        - postfix
        - su

    - name: "UPGRADE"
      yum: name=* state=latest

    - name: "BOOTSTRAP"
      yum: pkg={{ item }} state=latest
      with_items:
        - aria2
        - at
        - bzip2
        - ccze
        - corosync
        - git
        - iptraf
        - less
        - libselinux-python
        - links
        - man
        - most
        - mutt
        - net-snmp
        - nmap
        - ntp
        - ntpdate
        - open-vm-tools
        - rsync
        - sudo
        - tcpdump
        - tig
        - tmux
        - traceroute
        - tzdata
        - unzip
#        - epel-release
#        - net-snmp-utils

#    - name: "COPIANDO NTPD.CONF"
#       copy: src=/opt/ansible/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=644 backup=yes
#       notify: ntpd

    - name: "SELINUX PERMISSIVE"
      selinux: state=permissive policy=permissive

    - name: "CONFIGURANDO RELÓGIO"
      shell: ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      notify: ntpd

    - name: "CONFIGURANDO SNMP"
      shell: echo "rocommunity public" >> /etc/snmp/snmpd.conf
      notify: snmpd

  handlers:
    - name: "firewald"
      service: name=firewalld enabled=yes state=restarted

    - name: "ntpd"
      service: name=ntpd enabled=yes state=restarted

    - name: "snmpd"
      service: name=snmpd enabled=yes state=restarted

    - name: "sshd"
      service: name=sshd enabled=yes state=restarted
