---
- hosts: localhost

  tasks:
    - name: "HOSTNAME"
      hostname: name=django

    - name: "REMOVENDO PACOTES"
      yum: pkg={{ item }} state=absent
      with_items:
        - postfix
        - su
        - lynx
        - vi

    - name: "UPGRADE DOS PACOTES"
      yum: name=* state=latest

    - name: "INSTALANDO PACOTES NECESSARIOS"
      yum: pkg={{ item }} state=latest
      with_items:
        - aria2
        - at
        - bzip2
        - ccze
        - corosync
        - epel-release
        - git
        - htop
        - iptraf
        - less
        - libselinux-python
        - links
        - man
        - most
        - mutt
        - net-snmp
        - net-snmp-utils
        - nmap
        - ntp
        - ntpdate
        - open-vm-tools
        - openvm-tools-nox11
        - rsync
        - sudo
        - tcpdump
        - tig
        - tmux
        - traceroute
        - tzdata
        - unbound
        - unzip
        - vim
        - xzip
        # - openldap-clients
        # - dnf
        # - krb5-workstation
        # - net-tools
        # - nscd
        # - nss-pam-ldapd
        # - pam_krb5
        # - puppet

    - name: "SELINUX PERMISSIVE"
      selinux: state=permissive policy=permissive

    - name: "CONFIGURANDO MOUNTPOINT"
      shell: mount -t cifs //<machine-depot>/ansible -o user="FABIO",pass="",ro,vers=3.0 /mnt/ansible

    - name: "CONFIGURANDO SERVIDORES NTP"
      copy: src=/mnt/ansible/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=644 backup=yes
      notify: ntpd

    - name: "CONFIGURANDO TIMEZONE E RESTART NTPD"
      shell: ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      notify: ntpd

    - name: "CONFIGURANDO REALMD"
      copy: src=/mnt/ansible/realmd.conf dest=/etc/realmd.conf owner=root group=root mode=644 backup=yes

    - name: "CONFIGURANDO CACHE INTERNO DNS"
      copy: src=/mnt/ansible/forward.conf dest=/etc/unbound/forward.conf owner=root group=root mode=644 backup=yes
      # shell: echo "nameserver: 127.0.0.1" >> /etc/resolv.conf
      notify: unbound

    - name: "INICIANDO A TROCA DE TICKET COM O KDC"
      shell: kinit administrator

    - name: "INGRESSANDO O SERVIDOR NO DOMINIO"
      shell: realm join -v {{ domain }}

    - name: "CONFIGURANDO SNMP"
      shell: echo "rocommunity public" >> /etc/snmp/snmpd.conf
      notify: snmpd

      notify: unbound

  handlers:
    - name: "firewald"
      service: name=firewalld enabled=yes state=restarted

    - name: "ntpd"
      service: name=ntpd enabled=yes state=restarted

    - name: "snmpd"
      service: name=snmpd enabled=yes state=restarted

    - name: "sshd"
      service: name=sshd enabled=yes state=restarted

    -name: "unbound"
      service: name=unbound enabled=yes state=started
